### ISSUE TITLE
Please update PIP

### ISSUE THREAD

**Issue by The-Loeki** [dmsimard/python-cephclient#18]
Hi!

Can you please update PIP with the latest & greatest python-cephclient?

Thanks in advance!

**Comment by dmsimard** [comment]
Great idea, some features are indeed only in the master branch - will try and do it soon.

**Comment by dmsimard** [comment]
Hi !
I've drafted a new release, available @
- Github: https://github.com/dmsimard/python-cephclient/releases/tag/v0.1.0.5
- PyPi: https://pypi.python.org/pypi/python-cephclient/0.1.0.5

I even did some code cleanup and bug fixing prior to release as a bonus :)

Thanks and let me know if you have any feedback !
